#!/bin/bash

SCRIPT_DIR=$(realpath $(dirname $BASH_SOURCE))
CONFIGS=$SCRIPT_DIR/configs
LISTS_DIR=$SCRIPT_DIR/lists
AUR=$LISTS_DIR/aur
PYTHON=$LISTS_DIR/python
PACMAN=$LISTS_DIR/pacman
UCONFIG=$LISTS_DIR/uconfig
SCONFIG=$LISTS_DIR/sconfig

check_files_presence() {
  for file in "$@"; do
    if [ ! -f $file ]; then
      echo "Missing required file: $file" >&2
      exit 1
    fi
  done
}

check_files_presence $AUR $PACMAN $PYTHON $UCONFIG $SCONFIG

if [ ! -d $CONFIGS ]; then
  echo "Missing configuration files: $CONFIGS" >&2
  exit 1
fi

sudo pacman -S --needed --noconfirm --overwrite "*" - <$PACMAN

if ! [ $? -eq 0 ]; then
  exit 1
fi

if ! type yay 2>/dev/null; then
  YAY_CLONE_PATH=$SCRIPT_DIR/yay
  YAY_REPO_URL=https://aur.archlinux.org/yay-bin.git

  if [ -f $YAY_CLONE_PATH ]; then
    rm -rfv $YAY_CLONE_PATH
  fi

  git clone $YAY_REPO_URL $YAY_CLONE_PATH &&
    cd $YAY_CLONE_PATH &&
    makepkg -si --clean --noconfirm &&
    cd .. &&
    rm -rfv $YAY_CLONE_PATH &&
    yay -S --needed --noconfirm - <$AUR
fi

# user configuratoin files
while IFS=: read -r filename destination; do
  SRC=$CONFIGS/$filename
  DST=~/$destination
  DST_PARENT_NODE=$(dirname $DST)

  mkdir -pv $DST_PARENT_NODE

  if [ -d $DST ]; then
    rm -rfv $DST
  fi

  if [ "$1" = "--symlink" ] || [ "$1" = "-s" ]; then
    cp -rv --remove-destination --symbolic-link $SRC $DST
  else
    cp -rv --remove-destination $SRC $DST
  fi

done <"$UCONFIG"

# system wide configuration files
while IFS=: read -r filename destination; do
  SRC=$CONFIGS/$filename
  DST_PARENT_NODE=$(dirname $destination)
  sudo mkdir -pv $DST_PARENT_NODE
  sudo cp -rv --remove-destination $SRC $destination
done <"$SCONFIG"

pip install -r $PYTHON

git clone https://github.com/tmux-plugins/tmp ~/.tmux/plugins/tpm &&
  ~/.tmux/plugins/tpm/scripts/install_plugins.sh

sudo grub-mkconfig -o /boot/grub/grub.cfg
